---
abstract: 'Convert sql into a popup menu or radio group.'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-HTML-PopupRadio
provides:
  DBIx::HTML::PopupRadio:
    file: lib/DBIx/HTML/PopupRadio.pm
    version: 1.16
requires:
  Carp: 0
  HTML::Entities::Interpolate: 1
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.16
