--- #YAML:1.0
name: DBIx-HTML-PopupRadio
version: 1.09
author:
  - Ron Savage <ron@savage.net.au>
abstract: Convert sql into a popup menu or radio group.
license: artistic
requires:
  Carp: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides: {}
generated_by: Module::Build version 0.24
